PYTHONPATH=src python3 -m unittest discover -v -s tests
# PYTHONPATH=src python3 -m unittest tests/test_helper.py -v
# PYTHONPATH=src python3 -m unittest tests.test_helper.TestHelper.test_paragraphs -v
# PYTHONPATH=src python3 -m unittest tests.test_helper.TestHelper.test_codeblock -v
# PYTHONPATH=src python3 -m unittest tests.test_helper.TestHelper.test_heading_h1 -v
# PYTHONPATH=src python3 -m unittest tests.test_helper.TestHelper.test_quote_multiline -v
# PYTHONPATH=src python3 -m unittest tests.test_helper.TestHelper.test_unordered_list_basic -v
# PYTHONPATH=src python3 -m unittest tests.test_helper.TestHelper.test_block_to_block_type_unordered_list -v
# PYTHONPATH=src python3 -m unittest tests.test_helper.TestHelper.test_ordered_list_incrementing -v